AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    c75f97e4-a70d-46f3-8dd3-db3e85a4af9f:
      size:
        width: 60
        height: 60
      position:
        x: 349
        'y': 68
      z: 0
      embeds: []
    893e0da7-4120-407d-9cfc-bb785117cbe4:
      size:
        width: 60
        height: 60
      position:
        x: 470
        'y': 70
      z: 0
      embeds: []
    e9cbce10-7096-4eb2-a1ee-c8cc471cab37:
      size:
        width: 60
        height: 60
      position:
        x: 390
        'y': 170
      z: 0
    72df5c5b-120b-4b6c-b15f-bdbc74b1d672:
      size:
        width: 60
        height: 60
      position:
        x: 202
        'y': 76
      z: 0
    53dd5c32-b39f-43d9-a2a2-36c25317a227:
      size:
        width: 60
        height: 60
      position:
        x: 246
        'y': 166
      z: 0
Resources:
  B1:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c75f97e4-a70d-46f3-8dd3-db3e85a4af9f
  B2:
    Type: 'AWS::S3::Bucket'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c75f97e4-a70d-46f3-8dd3-db3e85a4af9f
    DeletionPolicy: Retain
  LF1:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: hw3-code
        S3Key: LF1.zip
      FunctionName: LF1_release
      Handler: lambda_fuLFnction.lambda_handler
      Role: arn:aws:iam::866169513932:role/service-role/lambda_1-role-j9b148m9
      Runtime: python3.6
  LF2:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: hw3-code
        S3Key: LF2.zip
      FunctionName: LF2_release
      Handler: lambda_fuLFnction.lambda_handler
      Role: arn:aws:iam::866169513932:role/service-role/lambda_1-role-j9b148m9
      Runtime: python3.6
  vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 13.0.0.0/16
    Metadata:
      AWS::CloudFormation::Designer:
        id: c75f97e4-a70d-46f3-8dd3-db3e85a4af9f
  subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: vpc
      CidrBlock: 13.0.0.0/24
      AvailabilityZone: us-east-2a
    Metadata:
      AWS::CloudFormation::Designer:
        id: c75f97e4-a70d-46f3-8dd3-db3e85a4af9f
  mySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: sg_cf_hw3
      VpcId:
        Ref: vpc
      GroupName: sg_cf_hw3
      SecurityGroupIngress:
      - FromPort: '443'
        IpProtocol: tcp
        ToPort: '443'
        CidrIp: 13.0.0.0/24
    Metadata:
      AWS::CloudFormation::Designer:
        id: c75f97e4-a70d-46f3-8dd3-db3e85a4af9f
